"""Initial migration - all tables

Revision ID: 872cec7906da
Revises: 
Create Date: 2026-02-10 11:15:05.382969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872cec7906da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncc_companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='company_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ASSISTANT', 'FINANCE', 'DRIVER', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'UNAVAILABLE', name='user_status'), nullable=False),
    sa.Column('two_factor_code', sa.String(length=6), nullable=True),
    sa.Column('two_factor_expires', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ncc_company_id', sa.Uuid(), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('vehicle_make', sa.String(length=100), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_seats', sa.Integer(), nullable=False),
    sa.Column('vehicle_luggage_capacity', sa.Integer(), nullable=False),
    sa.Column('vehicle_fuel_type', sa.String(length=30), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('vehicle_inspection_date', sa.Date(), nullable=True),
    sa.Column('special_permits', sa.JSON(), nullable=True),
    sa.Column('rating_avg', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('total_km', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_rides', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ncc_company_id'], ['ncc_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('TO_ASSIGN', 'BOOKED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'CRITICAL', name='ride_status'), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_lat', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('pickup_lng', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('dropoff_address', sa.String(length=500), nullable=False),
    sa.Column('dropoff_lat', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('dropoff_lng', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('passenger_name', sa.String(length=200), nullable=True),
    sa.Column('passenger_phone', sa.String(length=30), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('route_type', sa.Enum('URBAN', 'EXTRA_URBAN', name='route_type'), nullable=True),
    sa.Column('distance_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('driver_share', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('critical_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('critical_resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('critical_resolution_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_scheduled_at'), 'rides', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ride_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ride_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=200), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_range'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_driver_id'), 'reviews', ['driver_id'], unique=False)
    op.create_table('ride_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ride_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_history_ride_id'), 'ride_history', ['ride_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_history_ride_id'), table_name='ride_history')
    op.drop_table('ride_history')
    op.drop_index(op.f('ix_reviews_driver_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_scheduled_at'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ncc_companies')
    # ### end Alembic commands ###
