"""add_booking_config_and_ride_booking_fields

Revision ID: fcc88d5c7c37
Revises: ba524c16ecc2
Create Date: 2026-02-10 22:35:20.921353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc88d5c7c37'
down_revision: Union[str, None] = 'ba524c16ecc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('booking_reference', sa.String(length=100), nullable=True))
    op.add_column('rides', sa.Column('booking_state_hash', sa.String(length=255), nullable=True))
    op.add_column('rides', sa.Column('booking_customer_ref', sa.String(length=100), nullable=True))
    op.add_column('rides', sa.Column('flight_number', sa.String(length=20), nullable=True))
    op.add_column('rides', sa.Column('booking_services', sa.JSON(), nullable=True))
    op.add_column('rides', sa.Column('booking_raw_payload', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_rides_booking_reference'), 'rides', ['booking_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_booking_reference'), table_name='rides')
    op.drop_column('rides', 'booking_raw_payload')
    op.drop_column('rides', 'booking_services')
    op.drop_column('rides', 'flight_number')
    op.drop_column('rides', 'booking_customer_ref')
    op.drop_column('rides', 'booking_state_hash')
    op.drop_column('rides', 'booking_reference')
    # ### end Alembic commands ###
